name: Test
on:
  pull_request:
    branches: [main]
    paths-ignore:
      - 'data/**'
      - 'requirements.txt'
      - 'README.md'

jobs:
  pull_and_run:
    runs-on: ubuntu-latest
    needs: build_and_push
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull dinkuma/assignments:latest

      - name: Run Docker container
        run: |
          OUTPUT=$(docker run dinkuma/assignments:latest)
          echo "Score:"
          echo "$OUTPUT"
          if [[ `echo "$OUTPUT 0.50" | awk '{print ($1 < $2)}'` == 1 ]]; then
            echo "Insufficient Accuracy" 
            exit 1
          fi
